# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: T-Shaped Journey
motto: It's a mission and a passion!
email: csonuryilmaz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, welcome to my blog. As being an avid software developer,
  my blog contains some notes, how-to docs and my point of view
  about software development, programming languages, computer 
  science topics and all tech related stuff. Thanks for visiting,
  and happy coding!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: csonuryilmaz
github_username: csonuryilmaz
stackoverflow_username: 1750142

google_analytics: UA-113899594-1
disqus:
  shortname: csonuryilmaz

# Build settings
markdown: kramdown
theme: jekyll-theme-modernist
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
